#= generated by Comonicon =#
function command_main(ARGS::Vector{String} = ARGS)
    ccall(:jl_exit_on_sigint, Cvoid, (Cint,), 0)
    var"##help#255" = if isempty(ARGS)
            1
        else
            -1
        end
    var"##version#256" = -1
    for i = 1:length(ARGS)
        x = ARGS[i]
        if x == "--help" || x == "-h"
            var"##help#255" = i
            break
        end
        if x == "--version" || x == "-V"
            var"##version#256" = i
            break
        end
    end
    if var"##help#255" >= 1
        print("\n  \e[94m\e[1mmain\e[22m\e[39m\n\n  \n\n\e[0m\e[1mUsage\e[22m\n\n  \e[94m\e[1mmain\e[22m\e[39m\e[96m [options]\e[39m \e[95m<x>\e[39m\n\n\e[0m\e[1mArgs\e[22m\n\n  \e[95m<x>\e[39m\n\n\e[0m\e[1mOptions\e[22m\n\n  \e[96m--flag\e[39m \e[95m<arg>\e[39m           . default is \e[36mfalse\e[39m.\n\n  \e[96m--opt1\e[39m \e[95m<arg>\e[39m           . default is \e[36m1\e[39m.\n\n  \e[96m--opt2\e[39m \e[95m<arg::Int64>\e[39m    . default is \e[36m2\e[39m.\n\n\e[0m\e[1mFlags\e[22m\n\n  \e[96m-h, --help\e[39m             print this help message\n\n  \e[96m-V, --version\e[39m          print version information\n\n\n")
        return 0
    end
    if var"##version#256" >= 1
        println("\e[94m\e[1mmain\e[22m\e[39m")
        return 0
    end
    var"##parameters#257" = []
    var"##index#260" = 1
    while !(isempty(ARGS)) && 1 <= var"##index#260" <= length(ARGS)
        var"##arg#259" = ARGS[var"##index#260"]
        if startswith(var"##arg#259", "-")
            var"##m#261" = match(r"^--opt1$", var"##arg#259")
            if var"##m#261" === nothing
                var"##m#262" = match(r"^--opt1=(.*)", var"##arg#259")
                if var"##m#262" === nothing
                    var"##m#263" = match(r"^--opt2$", var"##arg#259")
                    if var"##m#263" === nothing
                        var"##m#264" = match(r"^--opt2=(.*)", var"##arg#259")
                        if var"##m#264" === nothing
                            var"##m#265" = match(r"^--flag$", var"##arg#259")
                            if var"##m#265" === nothing
                                var"##m#266" = match(r"^--flag=(.*)", var"##arg#259")
                                if var"##m#266" === nothing
                                    printstyled("Error: unknown option: $(var"##arg#259"), use -h or --help to check more detailed help info"; color = :red, bold = true)
                                    print("\n  \e[94m\e[1mmain\e[22m\e[39m\e[96m [options]\e[39m \e[95m<x>\e[39m\n\n  \n\n\e[0m\e[1mArgs\e[22m\n\n  \e[95m<x>\e[39m\n\n\e[0m\e[1mOptions\e[22m\n\n  \e[96m--flag\e[39m \e[95m<arg>\e[39m           . default is \e[36mfalse\e[39m.\n\n  \e[96m--opt1\e[39m \e[95m<arg>\e[39m           . default is \e[36m1\e[39m.\n\n  \e[96m--opt2\e[39m \e[95m<arg::Int64>\e[39m    . default is \e[36m2\e[39m.\n\n\e[0m\e[1mFlags\e[22m\n\n  \e[96m-h, --help\e[39m             print this help message\n\n\n")
                                    return 1
                                else
                                    push!(var"##parameters#257", :flag => String(var"##m#266"[1]))
                                    deleteat!(ARGS, var"##index#260")
                                    var"##index#260" = var"##index#260" - 1
                                end
                            else
                                var"##index#260" < length(ARGS) || error("expect an argument")
                                push!(var"##parameters#257", :flag => ARGS[var"##index#260" + 1])
                                deleteat!(ARGS, (var"##index#260", var"##index#260" + 1))
                                var"##index#260" = var"##index#260" - 1
                            end
                        else
                            push!(var"##parameters#257", :opt2 => convert(Int64, Meta.parse(String(var"##m#264"[1]))))
                            deleteat!(ARGS, var"##index#260")
                            var"##index#260" = var"##index#260" - 1
                        end
                    else
                        var"##index#260" < length(ARGS) || error("expect an argument")
                        push!(var"##parameters#257", :opt2 => convert(Int64, Meta.parse(ARGS[var"##index#260" + 1])))
                        deleteat!(ARGS, (var"##index#260", var"##index#260" + 1))
                        var"##index#260" = var"##index#260" - 1
                    end
                else
                    push!(var"##parameters#257", :opt1 => String(var"##m#262"[1]))
                    deleteat!(ARGS, var"##index#260")
                    var"##index#260" = var"##index#260" - 1
                end
            else
                var"##index#260" < length(ARGS) || error("expect an argument")
                push!(var"##parameters#257", :opt1 => ARGS[var"##index#260" + 1])
                deleteat!(ARGS, (var"##index#260", var"##index#260" + 1))
                var"##index#260" = var"##index#260" - 1
            end
        else
            var"##index#260" += 1
        end
    end
    var"##n_args#258" = length(ARGS) - 0
    if var"##n_args#258" < 1
        printstyled("Error: command main expect at least 1 arguments, got $(var"##n_args#258"), use -h or --help to check more detailed help info"; color = :red, bold = true)
        print("\n  \e[94m\e[1mmain\e[22m\e[39m\e[96m [options]\e[39m \e[95m<x>\e[39m\n\n  \n\n\e[0m\e[1mArgs\e[22m\n\n  \e[95m<x>\e[39m\n\n\e[0m\e[1mOptions\e[22m\n\n  \e[96m--flag\e[39m \e[95m<arg>\e[39m           . default is \e[36mfalse\e[39m.\n\n  \e[96m--opt1\e[39m \e[95m<arg>\e[39m           . default is \e[36m1\e[39m.\n\n  \e[96m--opt2\e[39m \e[95m<arg::Int64>\e[39m    . default is \e[36m2\e[39m.\n\n\e[0m\e[1mFlags\e[22m\n\n  \e[96m-h, --help\e[39m             print this help message\n\n\n")
        return 1
    end
    if var"##n_args#258" > 1
        printstyled("Error: command main expect at most 1 arguments, got $(var"##n_args#258"), use -h or --help to check more detailed help info"; color = :red, bold = true)
        print("\n  \e[94m\e[1mmain\e[22m\e[39m\e[96m [options]\e[39m \e[95m<x>\e[39m\n\n  \n\n\e[0m\e[1mArgs\e[22m\n\n  \e[95m<x>\e[39m\n\n\e[0m\e[1mOptions\e[22m\n\n  \e[96m--flag\e[39m \e[95m<arg>\e[39m           . default is \e[36mfalse\e[39m.\n\n  \e[96m--opt1\e[39m \e[95m<arg>\e[39m           . default is \e[36m1\e[39m.\n\n  \e[96m--opt2\e[39m \e[95m<arg::Int64>\e[39m    . default is \e[36m2\e[39m.\n\n\e[0m\e[1mFlags\e[22m\n\n  \e[96m-h, --help\e[39m             print this help message\n\n\n")
        return 1
    end
    (main)(ARGS[1]; var"##parameters#257"...)
    return 0
end
command_main()
